name: productivity
description: App for my Self

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_flip_counter: ^0.2.5
  animated_path: ^0.0.2
  animations: ^2.0.7
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.5
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  ionicons: ^0.2.2
  lottie: ^2.2.0
  multiple_stream_builder: ^3.0.2
  provider: ^6.0.5
  uuid: ^3.0.7
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  assets:
    - "assets/human.png"
    - "assets/pp.jpg"
