name: productivity
description: App for my Self

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  ionicons: ^0.2.1
  google_fonts: ^3.0.1
  provider: ^6.0.4
  animations: ^2.0.7
  animate_do: ^2.1.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  uuid: 3.0.6
  multiple_stream_builder: ^3.0.2
  flutter_countdown_timer: ^4.1.0
  animated_path: ^0.0.2
  go_router: ^6.0.0
  animated_flip_counter: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  fonts:
   - family: MyFlutterApp
     fonts:
      - asset: assets/fonts/MyFlutterApp.ttf
  assets:
    - "assets/human.png"
    - "assets/pp.jpg"
